// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReactionController from "./reaction_controller"
application.register("reaction", ReactionController)

import TextareaController from "./textarea_controller"
application.register("textarea", TextareaController)
