// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import ProgressBarController from "./progress_bar_controller"
application.register("progress-bar", ProgressBarController)

import TextareaController from "./textarea_controller"
application.register("textarea", TextareaController)
